# Rustfmt configuration for hisiflash
# https://rust-lang.github.io/rustfmt/

edition = "2024"
max_width = 100
tab_spaces = 4
newline_style = "Unix"

# Imports (stable options only)
reorder_imports = true
reorder_modules = true

# Match
match_block_trailing_comma = true

# Misc
use_small_heuristics = "Default"
use_field_init_shorthand = true
force_explicit_abi = true
